services:
  - docker
script:
- export REPO=securecodebox/amass
- export TAG=$TRAVIS_BRANCH
- echo -en "travis_fold:start:Docker_Build\r"
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t $REPO:$TAG --build-arg=COMMIT_ID=$TRAVIS_COMMIT --build-arg=BRANCH=$TRAVIS_BRANCH --build-arg=REPOSITORY_URL="https://github.com/secureCodeBox/scanner-infrastructure-amass" .
- docker tag $REPO:$TAG $REPO:oss;
- docker tag $REPO:$TAG $REPO:latest;
- docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
- echo -en "travis_fold:end:Docker_Build\r"
- docker images
- docker push $REPO